### PR TITLE
Update security-trivy-iac-check.yaml

### PR DESCRIPTION
**Pull request by samidbb**
updated trivy scan timeout

### CODE REVIEW

**Review by rifisdfds — APPROVED** [review]
Should the scan be taking 30 minutes? 😳 
That's a lot of minutes to use up if the job will fail, but I assume that number has been set based on some data rather than randomly set

**Comment by samidbb** [comment]
> 30 minutes

randomly set.. what would recommend I have no idea..

**Comment by rifisdfds** [comment]
Me neither, but changing it here changes for all. And if a job usually takes 2m, has a problem and times out at the default 5m that isn't too bad. If it has to wait until 30m that is a lot of Actions minutes used up. The better solution would be to over-ride the value no the repo that is timing out but that would require modifying this workflow to take inputs

**Comment by Mik-Nord** [comment]
I agree with @rifisdfds, this is not the correct solution

**Pull request merged**
